[project]
name = "world-pop-fx-pipeline"
version = "0.1.0"
description = "Small ETL that joins World Bank population with FX rates to MXN"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
    "typer>=0.15.4",
]

